version: '3.8'
services:
  # nest-app:
  #   build:
  #     context: ./nestjs-app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000" # Expose NestJS on port 3000
    depends_on:
      - yt-dlp-service
    environment:
      - PYTHON_SERVICE_URL=http://yt-dlp-service:5001
    networks:
      - app-network

  yt-dlp-service:
    build:
      context: ./yt-dlp-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001" # Expose Python API on port 5001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
